# Generated by Django 3.2.19 on 2023-06-01 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
