# Generated by Django 3.2.19 on 2023-06-04 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
