version: "3"

services:
  teste-postgres-compose:
    image: postgres
    environment:
      POSTGRES_USER: fabricio
      POSTGRES_PASSWORD: 23071998
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - /home/fabricio/Documentos/fashion2/PostgreSQL
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
